//! x86-64 Mnemonic Enum
//!
//! Defines all supported x86-64 instruction mnemonics

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum X86Mnemonic {
    Nop,
    Add,
    Sub,
    And,
    Or,
    Xor,
    Mov,
    Push,
    Pop,
    Lea,
    Jmp,
    Call,
    Ret,
    Cmp,
    Test,
    Inc,
    Dec,
    Not,
    Neg,
    Adc,
    Sbb,
    Shl,
    Shr,
    Sal,
    Sar,
    Rol,
    Ror,
    Rcl,
    Rcr,
    Jcc,
    Movaps,
    Addps,
    Subps,
    Mulps,
    Maxps,
    Minps,
    Movss,
    Movsd,
    Addss,
    Addsd,
    Subss,
    Subsd,
    Mulss,
    Mulsd,
    Divss,
    Divsd,
    Sqrtss,
    Sqrtsd,
    Cmpss,
    Cmpsd,
    Paddq,
    Psubq,
    Pmuludq,
    Psllq,
    Psrlq,
    Psraq,
    Mul,
    Imul,
    Div,
    Idiv,
    Movs,
    Cmps,
    Scas,
    Lods,
    Stos,
    Xchg,
    Cmpxchg,
    Xadd,
    Lock,
    Syscall,
    Cpuid,
    Hlt,
    Int,
    Bswap,
    Bsf,
    Bsr,
    Popcnt,
    Cbw,
    Cwde,
    Cdqe,
    Cwd,
    Cdq,
    Cqo,
    Tzcnt,
    Lzcnt,
    Andn,
    Bextr,
    Blsi,
    Blsmsk,
    Blsr,
    Fld,
    Fst,
    Fstp,
    Fadd,
    Fsub,
    Fmul,
    Fdiv,
    Fsqrt,
    Fcom,
    Fcomp,
    Fxch,
    Finit,
    In,
    Out,
    Cli,
    Sti,
    Pushf,
    Popf,
    Lahf,
    Sahf,
    Rdtsc,
    Rdtscp,
    Rdmsr,
    Wrmsr,
    Rdrand,
    Rdseed,
    Xbegin,
    Xend,
    Xabort,
    Xtest,
    Vfmaddpd,
    Vfmaddps,
    Vfmsubpd,
    Vfmsubps,
    Vfnmaddpd,
    Vfnmaddps,
    Vfnmsubpd,
    Vfnmsubps,
    Vaddps512,
    Vaddpd512,
    Vsubps512,
    Vsubpd512,
    Vmulps512,
    Vmulpd512,
    Vdivps512,
    Vdivpd512,
    Vsqrtps512,
    Vsqrtpd512,
    Vmaxps512,
    Vmaxpd512,
    Vminps512,
    Vminpd512,
    Vcompressps,
    Vcompresspd,
    Vexpandps,
    Vexpandpd,
    Vpermps512,
    Vpermpd512,
    Vblendmps,
    Vblendmpd,
    Vshuff32x4,
    Vshuff64x2,
    Kand,
    Kandn,
    Kor,
    Kxnor,
    Kxor,
    Kadd,
    Ksub,
    Kmov,
    Ktest,
    Tileloadd,
    Tileloaddt1,
    Tilestored,
    Tdpbf16ps,
    Tdpfp16ps,
    Vfrczpd,
    Vfrczps,
    Vpermil2pd,
    Vpermil2ps,
    Vpcmov,
    Vprot,
    Blcfill,
    Blci,
    Blcic,
    Blcmsk,
    Blsfill,
    Blsic,
    Tzmsk,
    Extrq,
    Insertq,
    Movntsd,
    Movntss,
}

impl std::str::FromStr for X86Mnemonic {
    type Err = ();
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "nop" => Ok(X86Mnemonic::Nop),
            "add" => Ok(X86Mnemonic::Add),
            "sub" => Ok(X86Mnemonic::Sub),
            "and" => Ok(X86Mnemonic::And),
            "or" => Ok(X86Mnemonic::Or),
            "xor" => Ok(X86Mnemonic::Xor),
            "mov" => Ok(X86Mnemonic::Mov),
            "push" => Ok(X86Mnemonic::Push),
            "pop" => Ok(X86Mnemonic::Pop),
            "lea" => Ok(X86Mnemonic::Lea),
            "jmp" => Ok(X86Mnemonic::Jmp),
            "call" => Ok(X86Mnemonic::Call),
            "ret" => Ok(X86Mnemonic::Ret),
            "cmp" => Ok(X86Mnemonic::Cmp),
            "test" => Ok(X86Mnemonic::Test),
            "inc" => Ok(X86Mnemonic::Inc),
            "dec" => Ok(X86Mnemonic::Dec),
            "not" => Ok(X86Mnemonic::Not),
            "neg" => Ok(X86Mnemonic::Neg),
            "jcc" => Ok(X86Mnemonic::Jcc),
            "movaps" => Ok(X86Mnemonic::Movaps),
            "addps" => Ok(X86Mnemonic::Addps),
            "subps" => Ok(X86Mnemonic::Subps),
            "mulps" => Ok(X86Mnemonic::Mulps),
            "maxps" => Ok(X86Mnemonic::Maxps),
            "minps" => Ok(X86Mnemonic::Minps),
            "mul" => Ok(X86Mnemonic::Mul),
            "imul" => Ok(X86Mnemonic::Imul),
            "div" => Ok(X86Mnemonic::Div),
            "idiv" => Ok(X86Mnemonic::Idiv),
            "xchg" => Ok(X86Mnemonic::Xchg),
            "cmpxchg" => Ok(X86Mnemonic::Cmpxchg),
            "xadd" => Ok(X86Mnemonic::Xadd),
            "lock" => Ok(X86Mnemonic::Lock),
            "syscall" => Ok(X86Mnemonic::Syscall),
            "cpuid" => Ok(X86Mnemonic::Cpuid),
            "hlt" => Ok(X86Mnemonic::Hlt),
            "int" => Ok(X86Mnemonic::Int),
            "adc" => Ok(X86Mnemonic::Adc),
            "sbb" => Ok(X86Mnemonic::Sbb),
            "shl" => Ok(X86Mnemonic::Shl),
            "shr" => Ok(X86Mnemonic::Shr),
            "sal" => Ok(X86Mnemonic::Sal),
            "sar" => Ok(X86Mnemonic::Sar),
            "rol" => Ok(X86Mnemonic::Rol),
            "ror" => Ok(X86Mnemonic::Ror),
            "rcl" => Ok(X86Mnemonic::Rcl),
            "rcr" => Ok(X86Mnemonic::Rcr),
            "movs" => Ok(X86Mnemonic::Movs),
            "cmps" => Ok(X86Mnemonic::Cmps),
            "scas" => Ok(X86Mnemonic::Scas),
            "lods" => Ok(X86Mnemonic::Lods),
            "stos" => Ok(X86Mnemonic::Stos),
            "movss" => Ok(X86Mnemonic::Movss),
            "movsd" => Ok(X86Mnemonic::Movsd),
            "addss" => Ok(X86Mnemonic::Addss),
            "addsd" => Ok(X86Mnemonic::Addsd),
            "subss" => Ok(X86Mnemonic::Subss),
            "subsd" => Ok(X86Mnemonic::Subsd),
            "mulss" => Ok(X86Mnemonic::Mulss),
            "mulsd" => Ok(X86Mnemonic::Mulsd),
            "divss" => Ok(X86Mnemonic::Divss),
            "divsd" => Ok(X86Mnemonic::Divsd),
            "sqrtss" => Ok(X86Mnemonic::Sqrtss),
            "sqrtsd" => Ok(X86Mnemonic::Sqrtsd),
            "cmpss" => Ok(X86Mnemonic::Cmpss),
            "cmpsd" => Ok(X86Mnemonic::Cmpsd),
            "bswap" => Ok(X86Mnemonic::Bswap),
            "bsf" => Ok(X86Mnemonic::Bsf),
            "bsr" => Ok(X86Mnemonic::Bsr),
            "popcnt" => Ok(X86Mnemonic::Popcnt),
            "cbw" => Ok(X86Mnemonic::Cbw),
            "cwde" => Ok(X86Mnemonic::Cwde),
            "cdqe" => Ok(X86Mnemonic::Cdqe),
            "cwd" => Ok(X86Mnemonic::Cwd),
            "cdq" => Ok(X86Mnemonic::Cdq),
            "cqo" => Ok(X86Mnemonic::Cqo),
            "tzcnt" => Ok(X86Mnemonic::Tzcnt),
            "lzcnt" => Ok(X86Mnemonic::Lzcnt),
            "andn" => Ok(X86Mnemonic::Andn),
            "bextr" => Ok(X86Mnemonic::Bextr),
            "blsi" => Ok(X86Mnemonic::Blsi),
            "blsmsk" => Ok(X86Mnemonic::Blsmsk),
            "blsr" => Ok(X86Mnemonic::Blsr),
            "fld" => Ok(X86Mnemonic::Fld),
            "fst" => Ok(X86Mnemonic::Fst),
            "fstp" => Ok(X86Mnemonic::Fstp),
            "fadd" => Ok(X86Mnemonic::Fadd),
            "fsub" => Ok(X86Mnemonic::Fsub),
            "fmul" => Ok(X86Mnemonic::Fmul),
            "fdiv" => Ok(X86Mnemonic::Fdiv),
            "fsqrt" => Ok(X86Mnemonic::Fsqrt),
            "fcom" => Ok(X86Mnemonic::Fcom),
            "fcomp" => Ok(X86Mnemonic::Fcomp),
            "fxch" => Ok(X86Mnemonic::Fxch),
            "finit" => Ok(X86Mnemonic::Finit),
            "in" => Ok(X86Mnemonic::In),
            "out" => Ok(X86Mnemonic::Out),
            "cli" => Ok(X86Mnemonic::Cli),
            "sti" => Ok(X86Mnemonic::Sti),
            "pushf" => Ok(X86Mnemonic::Pushf),
            "popf" => Ok(X86Mnemonic::Popf),
            "lahf" => Ok(X86Mnemonic::Lahf),
            "sahf" => Ok(X86Mnemonic::Sahf),
            "rdtsc" => Ok(X86Mnemonic::Rdtsc),
            "rdtscp" => Ok(X86Mnemonic::Rdtscp),
            "rdmsr" => Ok(X86Mnemonic::Rdmsr),
            "wrmsr" => Ok(X86Mnemonic::Wrmsr),
            "rdrand" => Ok(X86Mnemonic::Rdrand),
            "rdseed" => Ok(X86Mnemonic::Rdseed),
            "xbegin" => Ok(X86Mnemonic::Xbegin),
            "xend" => Ok(X86Mnemonic::Xend),
            "xabort" => Ok(X86Mnemonic::Xabort),
            "xtest" => Ok(X86Mnemonic::Xtest),
            "vfmaddpd" => Ok(X86Mnemonic::Vfmaddpd),
            "vfmaddps" => Ok(X86Mnemonic::Vfmaddps),
            "vfmsubpd" => Ok(X86Mnemonic::Vfmsubpd),
            "vfmsubps" => Ok(X86Mnemonic::Vfmsubps),
            "vfnmaddpd" => Ok(X86Mnemonic::Vfnmaddpd),
            "vfnmaddps" => Ok(X86Mnemonic::Vfnmaddps),
            "vfnmsubpd" => Ok(X86Mnemonic::Vfnmsubpd),
            "vfnmsubps" => Ok(X86Mnemonic::Vfnmsubps),
            "extrq" => Ok(X86Mnemonic::Extrq),
            "insertq" => Ok(X86Mnemonic::Insertq),
            "movntsd" => Ok(X86Mnemonic::Movntsd),
            "movntss" => Ok(X86Mnemonic::Movntss),
            "vaddps512" => Ok(X86Mnemonic::Vaddps512),
            "vaddpd512" => Ok(X86Mnemonic::Vaddpd512),
            "vsubps512" => Ok(X86Mnemonic::Vsubps512),
            "vsubpd512" => Ok(X86Mnemonic::Vsubpd512),
            "vmulps512" => Ok(X86Mnemonic::Vmulps512),
            "vmulpd512" => Ok(X86Mnemonic::Vmulpd512),
            "vdivps512" => Ok(X86Mnemonic::Vdivps512),
            "vdivpd512" => Ok(X86Mnemonic::Vdivpd512),
            "vsqrtps512" => Ok(X86Mnemonic::Vsqrtps512),
            "vsqrtpd512" => Ok(X86Mnemonic::Vsqrtpd512),
            "vmaxps512" => Ok(X86Mnemonic::Vmaxps512),
            "vmaxpd512" => Ok(X86Mnemonic::Vmaxpd512),
            "vminps512" => Ok(X86Mnemonic::Vminps512),
            "vminpd512" => Ok(X86Mnemonic::Vminpd512),
            "vcompressps" => Ok(X86Mnemonic::Vcompressps),
            "vcompresspd" => Ok(X86Mnemonic::Vcompresspd),
            "vexpandps" => Ok(X86Mnemonic::Vexpandps),
            "vexpandpd" => Ok(X86Mnemonic::Vexpandpd),
            "vpermps512" => Ok(X86Mnemonic::Vpermps512),
            "vpermpd512" => Ok(X86Mnemonic::Vpermpd512),
            "vblendmps" => Ok(X86Mnemonic::Vblendmps),
            "vblendmpd" => Ok(X86Mnemonic::Vblendmpd),
            "vshuff32x4" => Ok(X86Mnemonic::Vshuff32x4),
            "vshuff64x2" => Ok(X86Mnemonic::Vshuff64x2),
            "kand" => Ok(X86Mnemonic::Kand),
            "kandn" => Ok(X86Mnemonic::Kandn),
            "kor" => Ok(X86Mnemonic::Kor),
            "kxnor" => Ok(X86Mnemonic::Kxnor),
            "kxor" => Ok(X86Mnemonic::Kxor),
            "kadd" => Ok(X86Mnemonic::Kadd),
            "ksub" => Ok(X86Mnemonic::Ksub),
            "kmov" => Ok(X86Mnemonic::Kmov),
            "ktest" => Ok(X86Mnemonic::Ktest),
            "tileloadd" => Ok(X86Mnemonic::Tileloadd),
            "tileloaddt1" => Ok(X86Mnemonic::Tileloaddt1),
            "tilestored" => Ok(X86Mnemonic::Tilestored),
            "tdpbf16ps" => Ok(X86Mnemonic::Tdpbf16ps),
            "tdpfp16ps" => Ok(X86Mnemonic::Tdpfp16ps),
            "vfrczpd" => Ok(X86Mnemonic::Vfrczpd),
            "vfrczps" => Ok(X86Mnemonic::Vfrczps),
            "vpermil2pd" => Ok(X86Mnemonic::Vpermil2pd),
            "vpermil2ps" => Ok(X86Mnemonic::Vpermil2ps),
            "vpcmov" => Ok(X86Mnemonic::Vpcmov),
            "vprot" => Ok(X86Mnemonic::Vprot),
            "blcfill" => Ok(X86Mnemonic::Blcfill),
            "blci" => Ok(X86Mnemonic::Blci),
            "blcic" => Ok(X86Mnemonic::Blcic),
            "blcmsk" => Ok(X86Mnemonic::Blcmsk),
            "blsfill" => Ok(X86Mnemonic::Blsfill),
            "blsic" => Ok(X86Mnemonic::Blsic),
            "tzmsk" => Ok(X86Mnemonic::Tzmsk),
            "paddq" => Ok(X86Mnemonic::Paddq),
            "psubq" => Ok(X86Mnemonic::Psubq),
            "pmuludq" => Ok(X86Mnemonic::Pmuludq),
            "psllq" => Ok(X86Mnemonic::Psllq),
            "psrlq" => Ok(X86Mnemonic::Psrlq),
            "psraq" => Ok(X86Mnemonic::Psraq),
            _ => Err(()),
        }
    }
}
